name: Notify Slack on PR Activities

on:
  pull_request:
    types:
      - opened
      - closed
      - review_requested
      - review_comment_created
  pull_request_review:
    types:
      - submitted

jobs:
  send_slack_notification:
    runs-on: ubuntu-latest
    steps:
    - name: Determine PR Activity Type
      id: pr_activity
      run: |
        if [ "${{ github.event.action }}" = "closed" ] && [ "${{ github.event.pull_request.merged }}" = "true" ]; then
          echo "::set-output name=activity_type::merged"
        elif [ "${{ github.event.action }}" = "closed" ]; then
          echo "::set-output name=activity_type::closed"
        else
          echo "::set-output name=activity_type::${{ github.event.action }}"
        fi

    - name: Notify Slack
      uses: 8398a7/action-slack@v3
      with:
        status: custom
        fields: workflow,action
        custom_payload: |
          {
            "text": "${{ github.actor }} ${{ steps.pr_activity.outputs.activity_type }} a PR: <${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>"
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
