name: Notify Slack on PR Activities

on:
  pull_request:
    types:
      - opened
      - closed
      - review_requested
  pull_request_review:
    types:
      - submitted
  issue_comment:
    types:
      - created

jobs:
  send_slack_notification:
    if: github.event.issue.pull_request  # Only run for PR comments, not regular issue comments
    runs-on: ubuntu-latest
    steps:
    - name: Determine PR Activity Type
      id: pr_activity
      run: |
        if [ "${{ github.event.action }}" = "closed" ] && [ "${{ github.event.pull_request.merged }}" = "true" ]; then
          echo "::set-output name=activity_type::merged"
        elif [ "${{ github.event.action }}" = "closed" ]; then
          echo "::set-output name=activity_type::closed"
        elif [ "${{ github.event.action }}" = "created" ] && [ "${{ github.event_name }}" = "issue_comment" ]; then
          echo "::set-output name=activity_type::commented"
          echo "::set-output name=pr_url::${{ github.event.issue.html_url }}"
        else
          echo "::set-output name=activity_type::${{ github.event.action }}"
        fi

    - name: Notify Slack
      uses: 8398a7/action-slack@v3
      with:
        status: custom
        fields: workflow,action
        custom_payload: |
          {
            "text": "${{ github.actor }} ${{ steps.pr_activity.outputs.activity_type }} on a PR: <${{ steps.pr_activity.outputs.pr_url || github.event.pull_request.html_url }}|${{ github.event.pull_request.title || github.event.issue.title }}>"
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
